<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../StudioX.KeilImporter.csproj" />
    <Reference Include="StudioX.Extensions.Abstractions">
      <HintPath>$(StudioXSdkPath)</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>
</Project>
