<Project
  Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference
      Include="../StudioX.Packages/StudioX.Packages.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource
      Include="Resources/stm32-download.json" />
    <EmbeddedResource
      Include="Resources/studiox-stcgal-guard.py" />
    <EmbeddedResource
      Include="../../examples/packs/agm.ag32vf303-preview/debug/ag32vf303.cfg"
      LogicalName="StudioX.Engine.Ag32PinMapping.Target.cfg" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource
      Include="Resources/Lvgl/preview_host.c" />
  </ItemGroup>
</Project>
